### ISSUE TITLE
Full Date please!

### ISSUE THREAD

**Issue by cocker-cc** [lorenzovngl/FoodExpirationDates#14]
I have entered several Items together with their Expiration-Dates.  
The List unfortunately does not show the Year!

Please show  the full Date – preferably in standardized ISO-Date-Format: 2025-12-17

**Comment by lorenzovngl** [comment]
Hi,
Thank you for opening this issue. I have been thinking about what date format would be best for this project and thought that since most food expiration dates are weeks or months from the time of product purchase, there was no need to specify the year.

I realize, however, that this applies to products to be stored in the fridge, but so many other products that can be stored outside the fridge have expiration dates even longer than a year.

I will add the possibility to select a custom date format in the app settings.

**Comment by lorenzovngl** [comment]
Hi @cocker-cc, I finished the implementation of the functionality you've requested.
It will be available in the next release.

**Comment by cocker-cc** [comment]
Thanks for this Improvement.  
(I only now pulled the Foss-Version from IzzyOnDroid)
